### ISSUE TITLE
Concern

### ISSUE THREAD

**Issue by WycliffeAlphus** [Doreen-Onyango/zingiratech#18]
I have a concern about what is in the main repo so far. We need a structure of the files and how they should be arranged. A README if possible.  @karodgers has been doing the frontend. @kh3rld what you are focusing on at the moment. Clarity is needed to avoid confusions. For example, I have just seen a struct implementing the home page.

**Comment by Doreen-Onyango** [comment]
Working on the README file, I hope that helps alot.
Also @everyone ensure you are working on a different branch and make pull requests when need be.
This will help each person understand the flow of work.
